# Lab 5: Simulating an N-qubit system

## Introduction: Building on Single Qubit Systems

Last week, you built a `SingleQubitSystem` class that simulated quantum states and operations on a single qubit. You implemented core methods to initialize quantum states, inspect them (measuring probabilities), and apply quantum gates like Hadamard and Pauli-Z. This week, we're taking a significant step forward: you'll generalize that single-qubit simulator to handle an **arbitrary number of qubits**.

In the previous assignment, you were provided with substantial skeleton code that outlined the class structure, method signatures, and helper functions. This scaffolding allowed you to focus on understanding the quantum mechanics and implementing the core logic. **In this assignment, you will be expected to do everything yourself.** You'll implement all required methods, and write comprehensive tests.


The jump from single-qubit to N-qubit systems requires a fundamental shift in how you think about quantum state representation.

In the `SingleQubitSystem`, you could hardcode quantum gate matrices—a 2×2 matrix for single-qubit gates is simple and manageable. Now, with N qubits, gate matrices scale exponentially: an operation on an N-qubit system requires a 2^N × 2^N matrix. Rather than hardcoding these, you'll need to **programmatically construct** gate matrices and tensor products that generalize to any number of qubits.

Beyond extending existing operations, in this lab you will also implement:

- **Multi-qubit gates**: You'll implement the SWAP and the CNOT gates.
- **Quantum oracles**: You'll implement two oracles—the **BernVaz oracle** and the **Archimedes oracle**.

# Task 0: Swapping bits

Before we dive into quantum mechanics, let's build intuition for how **SWAP** operations work at the bit level. Understanding classical bit swapping will help you reason about the quantum SWAP gate you'll implement later.

We've provided you with a helper function that converts integers to binary strings in **big-endian**:


In [7]:
def int_to_bin_string(n: int, number_of_bits: int) -> str:
    """
    Convert an integer to a binary string in big-endian format.

    Args:
        n: The integer to convert
        number_of_bits: The length of the output binary string

    Returns:
        A binary string of length number_of_bits in big-endian format

    """
    return format(n, f'0{number_of_bits}b')



A 4-bit system (called a **nibble**) can represent 16 different states (0 through 15). Your task is to print a truth table showing what happens when you swap the bits at **index 0** and **index 2**.

The truth table should have three columns:

1. **Original**: The original 4-bit string
2. **After Swap**: The 4-bit string after swapping bits at positions 0 and 2
3. **Decimal**: The decimal value of the resulting bit string

In [8]:
# Format your table like this:
original = after_swap = int_to_bin_string(3,4)
print(f'{original}\t{after_swap}')

## TODO: Print the truth table after swapping bits at positions 0 and 2

def swap_bits(bit_string: str, i: int, j: int) -> str:
    bits = list(bit_string)
    bits[i], bits[j] = bits[j], bits[i]
    return "".join(bits)


print("Original\tAfter Swap\tDecimal")

for n in range(16):
    original = int_to_bin_string(n, 4)
    swapped = swap_bits(original, 0, 2)
    decimal = int(swapped, 2)

    print(f"{original}\t{swapped}\t{decimal}")



0011	0011
Original	After Swap	Decimal
0000	0000	0
0001	0001	1
0010	1000	8
0011	1001	9
0100	0100	4
0101	0101	5
0110	1100	12
0111	1101	13
1000	0010	2
1001	0011	3
1010	1010	10
1011	1011	11
1100	0110	6
1101	0111	7
1110	1110	14
1111	1111	15



Now that you've seen how bit swapping works at the classical level, think about how this concept might extend to quantum systems.

Consider these questions as you reflect:

1. **State representation**: In your `SingleQubitSystem`, you represented a quantum state as a state vector—a list of amplitudes, one for each possible classical state. How might you use bit swapping to rearrange the elements of an N-qubit state vector?
2. **Permutation and basis states**: When you swap bits in a classical state, you're essentially permuting which basis state corresponds to which computational outcome. If bit swapping changes the binary representation, how does that change *which* element of the state vector you're modifying?
3. **Generalizing to multiple qubits**: In a 2-qubit system, there are 4 basis states ($|00\rangle$, $|01\rangle$, $|10\rangle$, $|11\rangle$). If you wanted to swap qubits 0 and 1, how would the indices of your state vector elements need to be rearranged? Can you see a pattern that would work for *any* pair of qubits in an N-qubit system?
4. **Efficiency**: Rather than constructing a full $2^N \times 2^N$ matrix, could you implement SWAP by directly rearranging elements of a state vector? What would be the computational advantage?



## `NQubitSystem` technical specs

`NQubitSystem` is a concrete implementation that inherits from the abstract `QubitSystem` base class. It generalizes single-qubit operations to support quantum systems with an arbitrary number of qubits.


| Function | Behavior |
| :-- | :-- |
| `__init__(num_qubits: int)` | Initializes an N-qubit system with `num_qubits` qubits. The initial state should be the computational basis state $\lvert 0 \ldots 0 \rangle$ (all qubits in state $\lvert 0 \rangle$). Raise a `ValueError` if `num_qubits` is less than 1. |
| `set_value(value: list[float])` | Sets the system's quantum state. Accept a list of floats representing the state vector amplitudes in **big-endian** basis order. The length of the input must equal $2^{\text{num_qubits}}$. Implementations should validate that the input represents a valid state (i.e., the sum of squared amplitudes equals 1.0, within numerical precision) and raise a `ValueError` if not. |
| `get_value_braket() -> str` | Returns a bra-ket style string representing the current state. This is primarily for readability/debugging, you won't be penalized for stylistic differences or formatting. |
| `get_value_vector() -> list[float]` | Returns the current state vector amplitudes in big-endian basis order. |
| `apply_not(i: int) -> None` | Applies the NOT gate (Pauli-$X$) to qubit at index $i$, updating the system state. Raise an `IndexError` if $i$ is not a valid qubit index. |
| `apply_h(i: int) -> None` | Applies the Hadamard gate ($H$) to qubit at index $i$, updating the system state. Raise an `IndexError` if $i$ is not a valid qubit index. |
| `apply_z(i: int) -> None` | Applies the Pauli-$Z$ gate to qubit at index $i$, updating the system state. Raise an `IndexError` if $i$ is not a valid qubit index. |
| `apply_cnot(control: int, target: int) -> None` | Applies a controlled-NOT gate with `control` as the control qubit and `target` as the target qubit, updating the system state. Raise an `IndexError` if either index is invalid, or if they are the same. |
| `apply_swap(i: int, j: int) -> None` | Swaps qubits at indices $i$ and $j$, updating the system state. Raise an `IndexError` if either index is invalid, or if they are the same. |
| `measure() -> str` | <p>Simulates a measurement of the state of the system and returns one of the possible values as a big-endian string of binary. For example, if the state is $\lvert 000 \rangle$, the result would always be `'000'`. If the state is $\frac{1}{\sqrt{2}} \lvert 000 \rangle + \frac{1}{\sqrt{2}} \lvert 101 \rangle$, measurement would return `'000'` or `'101'` with equal probability (50% each).<ul><li>Note: If a system is in a state of superposition before `measure()`, the act of measurement should collapse the superposition.</li><li>Note 2: The output should always have the same number of bits as the system does. For a 3-qubit system, outputs will be 3-character strings like `'000'`, `'101'`, etc.</li></ul></p> |


## Using Numpy


As with last week's lab, you are free to use `numpy` to handle mathematical operations. You may **not** use `qiskit` or **any** other library besides `numpy` as part of your solution. **Adding extra `import` statements _will_ crash the autograder.**

You can perform vector-matrix multiplication with `numpy` as follows:

In [9]:
import numpy as np

# Define a state vector (e.g., |01⟩ for a 2-qubit system)
state = np.array([0, 1, 0, 0])

# Define a gate (e.g., a 2-qubit gate, X on the second qubit)
gate = np.array([[0, 1, 0, 0],
                 [1, 0, 0, 0],
                 [0, 0, 0, 1],
                 [0, 0, 1, 0]])

# Apply the gate to the state using matrix-vector multiplication (Note: Numpy treats vectors as row-vectors)
new_state = gate @ state
print(new_state)
# Output: [1 0 0 0]

# Alternatively, using np.dot()
new_state = np.dot(gate, state)
print(new_state)

[1 0 0 0]
[1 0 0 0]


To compute the tensor product (also called the Kronecker product):

In [10]:
import numpy as np

# Define two small matrices (e.g., single-qubit gates)
I = np.array([[1, 0],
              [0, 1]])

X = np.array([[0, 1],
              [1, 0]])

# Tensor product
result = np.kron(I, X)
print(result)

# Output:
#[[0 1 0 0]
# [1 0 0 0]
# [0 0 0 1]
# [0 0 1 0]]


[[0 1 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]]


## Task 1: Copy over your `QubitSystem` implementation from last week's assignment

In [11]:
## TODO: Paste QubitSystem here
from abc import ABC, abstractmethod
import random
import math
import numpy as np

class QubitSystem(ABC):
    """
    Abstract interface for a system of qubits.

    Child classes should store and update the quantum state, and must raise
    IndexError when gate indices are out of bounds.
    """

    def __init__(self, num_qubits: int):
        self._num_qubits = num_qubits
        self.state = [0]*2**num_qubits
        self.state[0] = 1

    @property
    def num_qubits(self) -> int:
        return self._num_qubits

    def _check_index(self, i: int) -> None:
        """Helper for consistent index-out-of-bounds behavior."""
        if i < 0 or i >= self._num_qubits:
            raise IndexError(f"Qubit index out of bounds: {i}")

    def _check_pair(self, i: int, j: int) -> None:
        """Helper for two-qubit operations."""
        self._check_index(i)
        self._check_index(j)

    @abstractmethod
    def set_value(self, value) -> None:
        """Set the current state using bra-ket string or state-vector list."""
        raise NotImplementedError

    @abstractmethod
    def get_value_braket(self) -> str:
        """Return a bra-ket formatted string for the current state."""
        raise NotImplementedError

    @abstractmethod
    def get_value_vector(self) -> list[float]:
        """Return the state vector (big-endian basis ordering)."""
        raise NotImplementedError

    @abstractmethod
    def apply_not(self, i: int) -> None:
        """Apply NOT (Pauli-X) to qubit i."""
        raise NotImplementedError

    @abstractmethod
    def apply_h(self, i: int) -> None:
        """Apply Hadamard to qubit i."""
        raise NotImplementedError

    @abstractmethod
    def apply_z(self, i: int) -> None:
        """Apply Pauli-Z to qubit i."""
        raise NotImplementedError

    @abstractmethod
    def apply_cnot(self, control: int, target: int) -> None:
        """Apply CNOT with given control and target qubits."""
        raise NotImplementedError

    @abstractmethod
    def apply_swap(self, i: int, j: int) -> None:
        """Swap qubits i and j."""
        raise NotImplementedError

    @abstractmethod
    def measure(self) -> str:
        """Simualte a measurement of the system."""
        raise NotImplementedError

class SingleQubitSystem(QubitSystem):
    def __init__(self):
        super().__init__(num_qubits=1)

    def set_value(self, value) -> None:
        """Set qubit state from a list or bra-ket string."""
        if isinstance(value, str):
            if value == "|0>":
                self.state = [1.0, 0.0]
            elif value == "|1>":
                self.state = [0.0, 1.0]
            elif value == "|+>":
                # |+> = (1/sqrt(2))|0> + (1/sqrt(2))|1>
                self.state = [1.0 / math.sqrt(2), 1.0 / math.sqrt(2)]
            elif value == "|->":
                # |-> = (1/sqrt(2))|0> - (1/sqrt(2))|1>
                self.state = [1.0 / math.sqrt(2), -1.0 / math.sqrt(2)]
            else:
                raise ValueError(f"Invalid bra-ket string: {value}")
        elif isinstance(value, list):
            if len(value) != 2:
                raise ValueError(f"Single qubit state must have 2 amplitudes, got {len(value)}")
            
            norm_sq = sum(abs(amp)**2 for amp in value)
            if not (0.99 <= norm_sq <= 1.01): 
                raise ValueError(f"State vector not normalized: sum of |amplitude|^2 = {norm_sq}")
            
            self.state = [float(amp) for amp in value]
        else:
            raise ValueError(f"Expected list or string, got {type(value)}")

    def get_value_braket(self) -> str:
        """Return bra-ket representation of the state."""
        alpha, beta = self.state[0], self.state[1]
        
        terms = []
        
        if abs(alpha) > 1e-10:
            if abs(abs(alpha) - 1.0) < 1e-10:
                terms.append("|0>")
            else:
                terms.append(f"{alpha:.4f}|0>")
        
        if abs(beta) > 1e-10:
            sign = "+" if beta > 0 else "-"
            abs_beta = abs(beta)
            if abs(abs_beta - 1.0) < 1e-10:
                if terms:
                    terms.append(f"{sign} |1>")
                else:
                    terms.append("|1>" if beta > 0 else "-|1>")
            else:
                if terms:
                    terms.append(f"{sign} {abs_beta:.4f}|1>")
                else:
                    terms.append(f"{beta:.4f}|1>")
        
        if not terms:
            return "0"
        
        return " ".join(terms)

    def get_value_vector(self) -> list[float]:
        """Return the state vector."""
        return self.state.copy()

    def apply_not(self, i: int) -> None:
        """Apply Pauli-X (NOT) gate to qubit i."""
        self._check_index(i)
        # NOT gate: |0> -> |1>, |1> -> |0>
        # Matrix: [[0, 1], [1, 0]]
        alpha, beta = self.state[0], self.state[1]
        self.state = [beta, alpha]

    def apply_h(self, i: int) -> None:
        """Apply Hadamard gate to qubit i."""
        self._check_index(i)
        # H = (1/sqrt(2)) * [[1, 1], [1, -1]]
        alpha, beta = self.state[0], self.state[1]
        inv_sqrt2 = 1.0 / math.sqrt(2)
        self.state = [
            inv_sqrt2 * (alpha + beta),
            inv_sqrt2 * (alpha - beta)
        ]

    def apply_z(self, i: int) -> None:
        """Apply Pauli-Z gate to qubit i."""
        self._check_index(i)
        # Z gate: Matrix [[1, 0], [0, -1]]
        alpha, beta = self.state[0], self.state[1]
        self.state = [alpha, -beta]

    def apply_cnot(self, control: int, target: int) -> None:
        """CNOT is not defined for single qubit system."""
        raise IndexError("Cannot apply CNOT to single-qubit system")

    def apply_swap(self, i: int, j: int) -> None:
        """SWAP is not defined for single qubit system."""
        raise IndexError("Cannot apply SWAP to single-qubit system")

    def measure(self) -> str:
        """Measure the qubit, collapsing the state."""
        alpha, beta = self.state[0], self.state[1]
        
        prob_0 = abs(alpha) ** 2
        
        if random.random() < prob_0:
            # Measure |0>
            self.state = [1.0, 0.0]
            return "0"
        else:
            # Measure |1>
            self.state = [0.0, 1.0]
            return "1"


## Task 2: Adapt your test suite from `SingleQubitSystem` for `NQubitSystem`
Just like last week, the autograder will expect the following tests to be present in your submission: `test_set_value`,`test_get_value_vector`,`test_apply_not`,`test_apply_h`,`test_apply_z`,`test_apply_cnot`,`test_apply_swap`,`test_measure`

In [12]:
## TODO: Implement your test suite here

def compare_lists(first_list, second_list, eps: float = 1e-3) -> bool:
    import numpy as np
    return bool(np.allclose(first_list, second_list, atol=eps, rtol=0.0))


def test_set_value() -> bool:
    # Arrange
    q2 = NQubitSystem(2)

    # Test 1: Valid 2-qubit state
    q2.set_value([1.0, 0.0, 0.0, 0.0])
    if not compare_lists(q2.state, [1.0, 0.0, 0.0, 0.0]):
        return False

    # Test 2: Valid superposition
    inv_sqrt2 = 1.0 / (2**0.5)
    q2.set_value([inv_sqrt2, 0.0, inv_sqrt2, 0.0])
    if not compare_lists(q2.state, [inv_sqrt2, 0.0, inv_sqrt2, 0.0]):
        return False

    # Test 3: Invalid length
    try:
        q2.set_value([1.0, 0.0, 0.0])
        return False
    except ValueError:
        pass

    # Test 4: Invalid normalization
    try:
        q2.set_value([2.0, 0.0, 0.0, 0.0])
        return False
    except ValueError:
        pass

    # Test 5: Invalid type
    try:
        q2.set_value("|00>")
        return False
    except ValueError:
        pass

    # Test 6: Valid 3-qubit state length
    q3 = NQubitSystem(3)
    q3.set_value([1.0] + [0.0]*7)
    if not compare_lists(q3.state, [1.0] + [0.0]*7):
        return False

    return True


def test_get_value_vector() -> bool:
    q = NQubitSystem(3)
    state = [0.0]*8
    state[5] = 1.0  # |101>
    q.set_value(state)

    vec = q.get_value_vector()
    if not compare_lists(vec, state):
        return False

    # Ensure copy
    vec[5] = 0.0
    if not compare_lists(q.state, state):
        return False

    return True


def test_apply_not() -> bool:
    q = NQubitSystem(2)

    # Test 1: NOT on qubit 0 maps |00> -> |10>
    q.set_value([1.0, 0.0, 0.0, 0.0])
    q.apply_not(0)
    if not compare_lists(q.state, [0.0, 0.0, 1.0, 0.0]):
        return False

    # Test 2: NOT on qubit 1 maps |00> -> |01>
    q.set_value([1.0, 0.0, 0.0, 0.0])
    q.apply_not(1)
    if not compare_lists(q.state, [0.0, 1.0, 0.0, 0.0]):
        return False

    # Test 3: Invalid index
    try:
        q.apply_not(2)
        return False
    except IndexError:
        pass

    try:
        q.apply_not(-1)
        return False
    except IndexError:
        pass

    return True


def test_apply_h() -> bool:
    q = NQubitSystem(2)
    inv_sqrt2 = 1.0 / (2**0.5)

    # Test 1: H on qubit 0: |00> -> (|00> + |10>)/sqrt2
    q.set_value([1.0, 0.0, 0.0, 0.0])
    q.apply_h(0)
    if not compare_lists(q.state, [inv_sqrt2, 0.0, inv_sqrt2, 0.0]):
        return False

    # Test 2: H on qubit 1: |00> -> (|00> + |01>)/sqrt2
    q.set_value([1.0, 0.0, 0.0, 0.0])
    q.apply_h(1)
    if not compare_lists(q.state, [inv_sqrt2, inv_sqrt2, 0.0, 0.0]):
        return False

    # Test 3: Invalid index
    try:
        q.apply_h(2)
        return False
    except IndexError:
        pass

    return True


def test_apply_z() -> bool:
    q = NQubitSystem(2)

    # Test 1: Z on qubit 0 flips phase of |10>
    q.set_value([0.0, 0.0, 1.0, 0.0])
    q.apply_z(0)
    if not compare_lists(q.state, [0.0, 0.0, -1.0, 0.0]):
        return False

    # Test 2: Z on qubit 1 flips phase of |01>
    q.set_value([0.0, 1.0, 0.0, 0.0])
    q.apply_z(1)
    if not compare_lists(q.state, [0.0, -1.0, 0.0, 0.0]):
        return False

    # Test 3: Invalid index
    try:
        q.apply_z(2)
        return False
    except IndexError:
        pass

    return True


def test_apply_cnot() -> bool:
    q = NQubitSystem(2)

    # Test 1: control 0 target 1, |10> -> |11>
    q.set_value([0.0, 0.0, 1.0, 0.0])
    q.apply_cnot(0, 1)
    if not compare_lists(q.state, [0.0, 0.0, 0.0, 1.0]):
        return False

    # Test 2: control 0 target 1, |00> unchanged
    q.set_value([1.0, 0.0, 0.0, 0.0])
    q.apply_cnot(0, 1)
    if not compare_lists(q.state, [1.0, 0.0, 0.0, 0.0]):
        return False

    # Test 3: Invalid indices
    try:
        q.apply_cnot(0, 0)
        return False
    except IndexError:
        pass

    try:
        q.apply_cnot(2, 1)
        return False
    except IndexError:
        pass

    return True


def test_apply_swap() -> bool:
    q = NQubitSystem(2)

    # Test 1: swap(0,1) on |01> -> |10>
    q.set_value([0.0, 1.0, 0.0, 0.0])
    q.apply_swap(0, 1)
    if not compare_lists(q.state, [0.0, 0.0, 1.0, 0.0]):
        return False

    # Test 2: Invalid indices
    try:
        q.apply_swap(0, 0)
        return False
    except IndexError:
        pass

    try:
        q.apply_swap(-1, 1)
        return False
    except IndexError:
        pass

    return True


def test_measure() -> bool:
    q = NQubitSystem(2)

    # Test 1: |00> always measures "00"
    q.set_value([1.0, 0.0, 0.0, 0.0])
    for _ in range(5):
        result = q.measure()
        if result != "00":
            return False
        if not compare_lists(q.state, [1.0, 0.0, 0.0, 0.0]):
            return False

    # Test 2: |11> always measures "11"
    q.set_value([0.0, 0.0, 0.0, 1.0])
    for _ in range(5):
        result = q.measure()
        if result != "11":
            return False
        if not compare_lists(q.state, [0.0, 0.0, 0.0, 1.0]):
            return False

    # Test 3: Superposition of |00> and |10>
    inv_sqrt2 = 1.0 / (2**0.5)
    for _ in range(20):
        q.set_value([inv_sqrt2, 0.0, inv_sqrt2, 0.0])
        result = q.measure()
        if result not in ["00", "10"]:
            return False
        if result == "00" and not compare_lists(q.state, [1.0, 0.0, 0.0, 0.0]):
            return False
        if result == "10" and not compare_lists(q.state, [0.0, 0.0, 1.0, 0.0]):
            return False

    return True



def run_tests() -> None:
    tests = [
        ("test_set_value", test_set_value),
        ("test_get_value_vector", test_get_value_vector),
        ("test_apply_not", test_apply_not),
        ("test_apply_h", test_apply_h),
        ("test_apply_z", test_apply_z),
        ("test_apply_cnot", test_apply_cnot),
        ("test_apply_swap", test_apply_swap),
        ("test_measure", test_measure),
    ]

    for name, fn in tests:
        try:
            result = fn()
        except Exception as e:
            print(f"Exception on {name}:", e)
            result = False

        print(f"{name}: {'PASS' if result else 'FAIL'}")

run_tests()


Exception on test_set_value: name 'NQubitSystem' is not defined
test_set_value: FAIL
Exception on test_get_value_vector: name 'NQubitSystem' is not defined
test_get_value_vector: FAIL
Exception on test_apply_not: name 'NQubitSystem' is not defined
test_apply_not: FAIL
Exception on test_apply_h: name 'NQubitSystem' is not defined
test_apply_h: FAIL
Exception on test_apply_z: name 'NQubitSystem' is not defined
test_apply_z: FAIL
Exception on test_apply_cnot: name 'NQubitSystem' is not defined
test_apply_cnot: FAIL
Exception on test_apply_swap: name 'NQubitSystem' is not defined
test_apply_swap: FAIL
Exception on test_measure: name 'NQubitSystem' is not defined
test_measure: FAIL


## Task 3: Implement `NQubitSystem`

In [13]:
## TODO: Implement NQubitSystem Here

class NQubitSystem(QubitSystem):
    def __init__(self, num_qubits: int):
        if num_qubits < 1:
            raise ValueError("num_qubits must be at least 1")
        super().__init__(num_qubits=num_qubits)

    def set_value(self, value) -> None:
        if not isinstance(value, list):
            raise ValueError(f"Expected list, got {type(value)}")

        expected_len = 2 ** self._num_qubits
        if len(value) != expected_len:
            raise ValueError(f"State vector must have length {expected_len}, got {len(value)}")

        norm_sq = sum(abs(amp) ** 2 for amp in value)
        if not (0.99 <= norm_sq <= 1.01):
            raise ValueError(f"State vector not normalized: sum of |amplitude|^2 = {norm_sq}")

        self.state = [float(amp) for amp in value]

    def get_value_braket(self) -> str:
        terms = []
        for idx, amp in enumerate(self.state):
            if abs(amp) <= 1e-10:
                continue
            basis = format(idx, f"0{self._num_qubits}b")
            sign = "-" if amp < 0 else "+"
            coeff = abs(amp)
            if not terms:
                if amp < 0:
                    terms.append(f"-{coeff:.4f}|{basis}>")
                else:
                    terms.append(f"{coeff:.4f}|{basis}>")
            else:
                terms.append(f" {sign} {coeff:.4f}|{basis}>")

        return "".join(terms) if terms else "0"

    def get_value_vector(self) -> list[float]:
        return self.state.copy()

    def apply_not(self, i: int) -> None:
        self._check_index(i)
        bitmask = 1 << (self._num_qubits - 1 - i)
        new_state = self.state.copy()
        for idx in range(len(self.state)):
            if (idx & bitmask) == 0:
                j = idx | bitmask
                new_state[idx], new_state[j] = new_state[j], new_state[idx]
        self.state = new_state

    def apply_h(self, i: int) -> None:
        self._check_index(i)
        bitmask = 1 << (self._num_qubits - 1 - i)
        inv_sqrt2 = 1.0 / math.sqrt(2)
        new_state = self.state.copy()
        for idx in range(len(self.state)):
            if (idx & bitmask) == 0:
                j = idx | bitmask
                a0 = self.state[idx]
                a1 = self.state[j]
                new_state[idx] = inv_sqrt2 * (a0 + a1)
                new_state[j] = inv_sqrt2 * (a0 - a1)
        self.state = new_state

    def apply_z(self, i: int) -> None:
        self._check_index(i)
        bitmask = 1 << (self._num_qubits - 1 - i)
        new_state = self.state.copy()
        for idx in range(len(self.state)):
            if (idx & bitmask) != 0:
                new_state[idx] = -new_state[idx]
        self.state = new_state

    def apply_cnot(self, control: int, target: int) -> None:
        self._check_pair(control, target)
        if control == target:
            raise IndexError("Control and target must be different")
        control_mask = 1 << (self._num_qubits - 1 - control)
        target_mask = 1 << (self._num_qubits - 1 - target)
        new_state = self.state.copy()
        for idx in range(len(self.state)):
            if (idx & control_mask) != 0 and (idx & target_mask) == 0:
                j = idx | target_mask
                new_state[idx], new_state[j] = new_state[j], new_state[idx]
        self.state = new_state

    def apply_swap(self, i: int, j: int) -> None:
        self._check_pair(i, j)
        if i == j:
            raise IndexError("Swap indices must be different")
        mask_i = 1 << (self._num_qubits - 1 - i)
        mask_j = 1 << (self._num_qubits - 1 - j)
        new_state = self.state.copy()
        for idx in range(len(self.state)):
            bit_i = (idx & mask_i) != 0
            bit_j = (idx & mask_j) != 0
            if bit_i != bit_j:
                swapped = idx ^ (mask_i | mask_j)
                if idx < swapped:
                    new_state[idx], new_state[swapped] = new_state[swapped], new_state[idx]
        self.state = new_state

    def measure(self) -> str:
        probs = [abs(amp) ** 2 for amp in self.state]
        r = random.random()
        cumulative = 0.0
        chosen = 0
        for idx, p in enumerate(probs):
            cumulative += p
            if r <= cumulative:
                chosen = idx
                break

        new_state = [0.0] * len(self.state)
        new_state[chosen] = 1.0
        self.state = new_state
        return format(chosen, f"0{self._num_qubits}b")


## Oracles:


In class we've discussed two quantum oracles: **BernVaz** and **Archimedes**. Notice how they share a common pattern:

1. **State Preparation**: Both oracles expect the system to be in a specific configuration. BernVaz, for example, expects all qubits must be in a superposition state (e.g., created by applying Hadamard gates to all qubits).
2. **Oracle Probing**: Once prepared, you apply the oracle itself, which transforms the superposed state according to the code(s) it encodes.
3. **Post-Processing**: After the oracle runs, the system requires additional quantum operations to extract useful information. In the case of BernVaz, this means applying Hadamard gates to all qubits again to collapse the superposition in a meaningful way.

Notice how both oracles follow this same high-level workflow, even though they encode different functions. This is precisely the kind of scenario where **object-oriented programming** shines.

## Interfaces: Capturing Shared Behavior

In OOP, an **interface** (called an abstract base class in python) defines a contract: "Any object that implements this interface must support these operations." Interfaces let you write code that works with *any* object following that contract, without needing to know the specific details of each implementation.

In our case, you might imagine defining an `Oracle` interface that specifies:

- An oracle must be able to prepare the system
- An oracle must be able to apply itself to a system
- An oracle must be able to post-process the result

Both `BernVazOracle` and `ArchimedesOracle` could implement this interface, each providing their own specific logic while adhering to the same structure. This way, future code could work with either oracle.

This pattern is powerful because it lets you **abstract away the differences** (number of qubits, specific gate sequences) while **capturing the similarities** (the three-step workflow). As quantum algorithms grow more complex, this kind of abstraction will help you manage complexity and extend your code without rewriting it.

# `Oracle` Abstract Base Class

Implement `Oracle` as an abstract base class (an `ABC` from the Python library `abc`) that defines the interface for quantum oracles (this means `Oracle` should consist entirely of `@abstractmethod`s). It is up to concrete oracle implementations to inherit from this class and provide concrete implementations of the three abstract methods.


| Function | Behavior |
| :-- | :-- |
| `__init__(codes: list[str])` | Initializes the oracle with a list of strings representing the 3-bit codes that define the oracle's behavior. Store these codes for use in the `probe()` method. |
| `pre_probe(system: NQubitSystem) -> None` | Prepares the quantum system into the state that the oracle expects. This typically involves creating an equal superposition across all qubits. Raise an `IndexError` if `system.num_qubits` is not equal to 4. |
| `probe(system: NQubitSystem) -> None` | Applies the oracle transformation to the system. The oracle uses the stored codes to determine how to transform each basis state. Raise an `IndexError` if `system.num_qubits` is not equal to 4. |
| `post_probe(system: NQubitSystem) -> None` | Performs post-processing on the system after the oracle has been applied. This typically involves applying additional gates (e.g., Hadamard gates) to extract meaningful information from the superposed state. Raise an `IndexError` if `system.num_qubits` is not equal to 4. |

## Task 4: Implement `Oracle` as an abstract base class

In [14]:
## TODO: Oracle code below

class Oracle(ABC):
    def __init__(self, codes: list[str]):
        self.codes = codes

    @abstractmethod
    def pre_probe(self, system: NQubitSystem) -> None:
        raise NotImplementedError

    @abstractmethod
    def probe(self, system: NQubitSystem) -> None:
        raise NotImplementedError

    @abstractmethod
    def post_probe(self, system: NQubitSystem) -> None:
        raise NotImplementedError


## Task 5: Implement the `BernVaz` oracle as a child of `Oracle`
![bern vaz oracle](https://www.classes.cs.uchicago.edu/archive/2026/winter/22880-1/assigns/week5/figs/bernvazoraclealg.png)

**Note**: We will only test your code with code lists containing a single 3 bit code (e.g., `['011']`). It is up to you to decide how to handle the case of lists containing multiple codes; you may choose to ignore that case or throw an `IndexError` exception.

In [15]:
## TODO: BernVaz code below

class BernVazOracle(Oracle):
    def __init__(self, codes: list[str]):
        super().__init__(codes=codes)

    def _validate(self, system: NQubitSystem) -> None:
        if system.num_qubits != 4:
            raise IndexError("BernVazOracle requires a 4-qubit system")
        if len(self.codes) != 1:
            raise IndexError("BernVazOracle expects a single 3-bit code")
        code = self.codes[0]
        if len(code) != 3 or any(c not in "01" for c in code):
            raise ValueError("Code must be a 3-bit string")

    def pre_probe(self, system: NQubitSystem) -> None:
        self._validate(system)
        system.apply_not(3)
        for i in range(4):
            system.apply_h(i)

    def probe(self, system: NQubitSystem) -> None:
        self._validate(system)
        code = self.codes[0]
        for i, bit in enumerate(code):
            if bit == "1":
                system.apply_cnot(i, 3)

    def post_probe(self, system: NQubitSystem) -> None:
        self._validate(system)
        for i in range(3):
            system.apply_h(i)


## Task 6: Implement the `Archimedes` oracle as a child of `Oracle`
![archimedes oracle](https://www.classes.cs.uchicago.edu/archive/2026/winter/22880-1/assigns/week5/figs/archoraclealg.png)


In [16]:
## TODO: Archimedes code below

class ArchimedesOracle(Oracle):
    def __init__(self, codes: list[str]):
        super().__init__(codes=codes)

    def _validate(self, system: NQubitSystem) -> None:
        if system.num_qubits != 4:
            raise IndexError("ArchimedesOracle requires a 4-qubit system")
        for code in self.codes:
            if len(code) != 3 or any(c not in "01" for c in code):
                raise ValueError("Each code must be a 3-bit string")

    def pre_probe(self, system: NQubitSystem) -> None:
        self._validate(system)
        system.apply_not(3)
        for i in range(4):
            system.apply_h(i)

    def _matches_code(self, idx: int, code: str, num_qubits: int) -> bool:
        for qi, bit in enumerate(code):
            mask = 1 << (num_qubits - 1 - qi)
            is_one = (idx & mask) != 0
            if (bit == "1") != is_one:
                return False
        return True

    def probe(self, system: NQubitSystem) -> None:
        self._validate(system)
        ancilla_mask = 1 << (system.num_qubits - 1 - 3)
        state = system.state.copy()
        for code in self.codes:
            new_state = state.copy()
            for idx in range(len(state)):
                ancilla_is_one = (idx & ancilla_mask) != 0
                if ancilla_is_one:
                    continue
                if self._matches_code(idx, code, system.num_qubits):
                    j = idx | ancilla_mask
                    new_state[idx], new_state[j] = new_state[j], new_state[idx]
            state = new_state
        system.state = state

    def post_probe(self, system: NQubitSystem) -> None:
        self._validate(system)
        for i in range(3):
            system.apply_h(i)


## Task 7: Test Your Oracles:

Finally, write tests to verify that your `Oracle` abstract base class and concrete oracle implementations work correctly. Implement the following:


| Test Name | Description |
| :-- | :-- |
| `test_oracle_is_abstract` | Verify that attempting to instantiate `Oracle` directly raises a `TypeError`. Since `Oracle` is an abstract base class, it should not be possible to create an instance of it without implementing all abstract methods. |
| `test_bernvaz_is_oracle` | Verify that `BernVazOracle` is a subclass of `Oracle` and can be instantiated with a valid list of 3-bit codes. |
| `test_archimedes_is_oracle` | Verify that `ArchimedesOracle` is a subclass of `Oracle` and can be instantiated with a valid list of 3-bit codes. |
| `test_bernvaz` | Create a 4-qubit `NQubitSystem`, prepare it using `BernVazOracle.pre_probe()`, apply the oracle using `BernVazOracle.probe()`, perform post-processing with `BernVazOracle.post_probe()`, then verify that the final state matches your expected result. Test with multiple different code lists to ensure correctness. |
| `test_archimedes` | Create a 4-qubit `NQubitSystem`, prepare it using `ArchimedesOracle.pre_probe()`, apply the oracle using `ArchimedesOracle.probe()`, perform post-processing with `ArchimedesOracle.post_probe()`, then verify that the final state matches your expected result. Test with multiple different code lists to ensure correctness. |




In [ ]:
## TODO: Oracle Tests

def compare_lists(first_list, second_list, eps: float = 1e-3) -> bool:
    import numpy as np
    return bool(np.allclose(first_list, second_list, atol=eps, rtol=0.0))


def test_oracle_is_abstract() -> bool:
    try:
        _ = Oracle(["000"])
        return False
    except TypeError:
        return True


def test_bernvaz_is_oracle() -> bool:
    if not issubclass(BernVazOracle, Oracle):
        return False
    bv = BernVazOracle(["010"])
    return isinstance(bv, Oracle)


def test_archimedes_is_oracle() -> bool:
    if not issubclass(ArchimedesOracle, Oracle):
        return False
    arch = ArchimedesOracle(["010"])
    return isinstance(arch, Oracle)


def _expected_bv_state(code: str) -> list[float]:
    inv_sqrt2 = 1.0 / (2**0.5)
    vec = [0.0] * 16
    idx0 = int(code + "0", 2)
    idx1 = int(code + "1", 2)
    vec[idx0] = inv_sqrt2
    vec[idx1] = -inv_sqrt2
    return vec


def test_bernvaz() -> bool:
    for code in ["000", "011", "101"]:
        system = NQubitSystem(4)
        oracle = BernVazOracle([code])
        oracle.pre_probe(system)
        oracle.probe(system)
        oracle.post_probe(system)
        expected = _expected_bv_state(code)
        if not compare_lists(system.state, expected):
            return False
    return True


def _apply_h_to_state(state: list[float], qubit: int, num_qubits: int) -> list[float]:
    inv_sqrt2 = 1.0 / (2**0.5)
    bitmask = 1 << (num_qubits - 1 - qubit)
    new_state = state.copy()
    for idx in range(len(state)):
        if (idx & bitmask) == 0:
            j = idx | bitmask
            a0 = state[idx]
            a1 = state[j]
            new_state[idx] = inv_sqrt2 * (a0 + a1)
            new_state[j] = inv_sqrt2 * (a0 - a1)
    return new_state


def _apply_x_to_state(state: list[float], qubit: int, num_qubits: int) -> list[float]:
    bitmask = 1 << (num_qubits - 1 - qubit)
    new_state = state.copy()
    for idx in range(len(state)):
        if (idx & bitmask) == 0:
            j = idx | bitmask
            new_state[idx], new_state[j] = new_state[j], new_state[idx]
    return new_state


def _matches_code(idx: int, code: str, num_qubits: int) -> bool:
    for qi, bit in enumerate(code):
        mask = 1 << (num_qubits - 1 - qi)
        is_one = (idx & mask) != 0
        if (bit == "1") != is_one:
            return False
    return True


def _apply_archimedes_probe(state: list[float], codes: list[str], num_qubits: int) -> list[float]:
    ancilla_mask = 1 << (num_qubits - 1 - 3)
    current = state.copy()
    for code in codes:
        new_state = current.copy()
        for idx in range(len(current)):
            ancilla_is_one = (idx & ancilla_mask) != 0
            if ancilla_is_one:
                continue
            if _matches_code(idx, code, num_qubits):
                j = idx | ancilla_mask
                new_state[idx], new_state[j] = new_state[j], new_state[idx]
        current = new_state
    return current


def test_archimedes() -> bool:
    codes_list = [["000"], ["101"], ["011"]]
    for codes in codes_list:
        system = NQubitSystem(4)
        oracle = ArchimedesOracle(codes)

        oracle.pre_probe(system)
        oracle.probe(system)
        oracle.post_probe(system)

        # Build expected state independently
        state = [0.0] * 16
        state[0] = 1.0
        state = _apply_x_to_state(state, 3, 4)
        for i in range(4):
            state = _apply_h_to_state(state, i, 4)
        state = _apply_archimedes_probe(state, codes, 4)
        for i in range(3):
            state = _apply_h_to_state(state, i, 4)

        if not compare_lists(system.state, state):
            return False

    return True


def run_oracle_tests() -> None:
    tests = [
        ("test_oracle_is_abstract", test_oracle_is_abstract),
        ("test_bernvaz_is_oracle", test_bernvaz_is_oracle),
        ("test_archimedes_is_oracle", test_archimedes_is_oracle),
        ("test_bernvaz", test_bernvaz),
        ("test_archimedes", test_archimedes),
    ]

    for name, fn in tests:
        try:
            result = fn()
        except Exception as e:
            print(f"Exception on {name}:", e)
            result = False

        print(f"{name}: {'PASS' if result else 'FAIL'}")

run_oracle_tests()


# Submission
Congratulations on completing the lab!
Make sure you:


1.   Test all of your functions by calling them at least once.
2.   Download your lab as a **python** `.py` script (NOT an `.ipynb` file):
      
      ```File -> Download -> Download .py```

3.   Rename the downloaded file to `Lab5Answers.py`.
4.   Upload the `Lab5Answers.py` file to Gradescope.
5.   Ensure the autograder runs successfully.